### ISSUE TITLE
Create Test Data

### ISSUE THREAD

**Issue by remkohdev** [sparkrnyc/sparkr_mobile#16]
What type of test data can be created?  the json format that I would love to see for the test data (for notifications, profiles, projects and teams) can be seen here: https://github.com/sparkrnyc/sparkr_mobile/tree/master/src/assets/data

but additional properties might be required

**Comment by remkohdev** [comment]
Added test data, not complete but workable, see the 'providers/data/in-memory-db-test.ts' file

**Comment by EmilyLong03** [comment]
OK.
