### ISSUE TITLE
SignUp: action after SIGNUP button

### ISSUE THREAD

**Issue by olgabartnicki** [sparkrnyc/sparkr_mobile#74]
When I complete all fields and click "SIGNUP" button, rotating "Signing up" appears, rotates for some time, then leaves you on that same Sigup page. So it's unclear if you did or did not sign up.

**Comment by remkohdev** [comment]
Olga, can you add steps to reproduce and add some details like username/password and fields used to signup with, enter day/time of day, and exact steps you did:
1. ope the app, click the signup button
2. enter the following signup values:
- 
- 
- 
etc
3. click signup button
4. rotation gif appears, disappears, but am still on signup page

Likely you timed out, so it's useful to know how long if possible the rotation wheel showed.

**Comment by remkohdev** [comment]
Required fix: show error message during login/signup process. See bug #77 and #76 .

**Comment by remkohdev** [comment]
Solution is broken up in 2 steps:
1. Add error message when signup fails
2. Add modal popup when signup succeeds, see #10
