### ISSUE TITLE
SignUp fields: none are required

### ISSUE THREAD

**Issue by olgabartnicki** [sparkrnyc/sparkr_mobile#75]
I thought we planned on some fields to be required (Your Name, College). Currently, it doesn't check for any fields as required.

**Comment by remkohdev** [comment]
Correct, except for username/password in this version no other field validation is done. I left that for next iteration. Can you specify what validations you want done?

**Comment by olgabartnicki** [comment]
Require: 
First
Last 
College
Role

Validate:
email (or just require it for simplicity?)

Get rid of:
Username - use email as username instead, address people by first name

**Comment by remkohdev** [comment]
Required fields are checked, and when missing, signup will fail. No error messaging was displayed though, this was fixed in another fix now.
