### ISSUE TITLE
Flow: define Home page: what goes on the home page? my activity log? alerts?

### ISSUE THREAD

**Issue by remkohdev** [sparkrnyc/sparkr_mobile#9]

**Comment by aavetis** [comment]
just got a thought for something we could have on the main homepage (i think @remkohdev you called this mySparkr, i like that a lot)

we could have a section for like... "relevant news" or "upcoming events" or however we want to call it, but basically "stuff you should know about"

we can use that to:
- highlight new features coming to the app 
    - ex: `[FEATURE] You can now upload a blah blah to your profile!`
- events coming up
    - ex: `CUNY Startups is having a hackathon on the 35th of Nevruary, assemble your team with ..... etc.`
    - ex: `XYZ New York initiative is having a contest for [something], find teammates and submit your projects before the deadline on October 31st!`


to be continued...

**Comment by remkohdev** [comment]
Actually to simplify the homepage for now, i made the currentUser profileDetail page the homepage for now.
